### ISSUE TITLE
(WIP) update Missouri governor to Mike Parson (on 6/1)

### ISSUE THREAD

**Issue by AlJohri** [CivilServiceUSA/us-governors#4]
Eric Greitens resigned on May 29.

```yaml
votesmart: 39119
first_name: Michael
middle_name: L.
last_name: Parson
name_suffix:
goes_by: Mike
pronunciation: MIKE PAR-son
gender: male
ethnicity: white-american
religion: 
openley_lgbtq: no
date_of_birth: 1955-09-17
entered_office: 2018-06-01
term_end: 2019-01-01
biography:
phone: 
fax: 
latitude:
longitude:
address:
website: 
contact_page: 
facebook_url: https://www.facebook.com/TeamMikeParson/
twitter_url: https://twitter.com/mikeparson
photo_url: 
```

Sources:
- https://ballotpedia.org/Mike_Parson
- https://ltgov.mo.gov/
- https://votesmart.org/candidate/biography/39119/mike-parson
